server:
  port: 8082

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: ecommerce_user
    password: ecommerce_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    function:
      definition: inventoryReservedConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        inventoryReservedConsumer-in-0:
          destination: inventory-reserved-events
          group: payment-group