spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: ecommerce_user
    password: ecommerce_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # KAFKA CONFIGURATION
  cloud:
    function:
      definition: paymentSuccessConsumer;paymentFailureConsumer;inventoryFailureConsumer
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        # 1. Producer
        orderCreatedProducer-out-0:
          destination: order-created-events
          content-type: application/json
        # 2. Consumers
        paymentSuccessConsumer-in-0:
          destination: payment-success-events
          group: order-group
        paymentFailureConsumer-in-0:
          destination: payment-failed-events
          group: order-group
        inventoryFailureConsumer-in-0:
          destination: inventory-failed-events
          group: order-group